/* TypeScript mirrors of what the FastAPI routers actually return.
 *
 * These were not written from the endpoint source. They were generated by
 * CALLING each endpoint and dumping the shape of the response, because the
 * routers build their dicts inline with spreads (`{**it, ...}` in
 * api/queue.py), and reading that code gives you the keys you expect rather
 * than the keys that ship.
 *
 * Regenerate after any router change:
 *     python -m scripts.api_shapes
 *
 * Every interface below cites the endpoint it belongs to. If you find yourself
 * adding a field here that no endpoint returns, the field belongs in the
 * router first.
 */

/** One sensor on one station, ranked for an operator's attention.
 *  GET /api/queue -> items[] */
export interface QueueItem {
  id: string
  station: string
  /** short key: temp | pres | rh | volt | ltemp */
  sensor: string
  label: string
  unit: string
  /** logger_volt and logger_temp are housekeeping, not meteorology. They are
   *  the only evidence not derived from the three published numbers, which is
   *  what makes corroboration mean anything. */
  housekeeping: boolean
  severity: number
  rank: number
  bias: number
  drift_per_day: number
  noise: number
  /** Beta-reputation posterior mean in [0,1]. Low means the sensor has failed
   *  most of its recent checks, NOT that the reading is far from expected. */
  trust: number
  /** alpha + beta: weight of evidence behind `trust`. A trust of 0.4 on an
   *  evidence of 3 says almost nothing. */
  evidence: number
  checks: string
  onset: string
  days_since_onset: number
  action: 'DISPATCH' | 'CORRECT CENTRALLY' | string
  why: string
  confirmed_by_analyst: boolean
  analyst_subject: string
  window: { dqr: string; start: string; end: string }
  reference: ReferenceNote
}

/** How badly the trailing reference is compromised for this particular window.
 *  A fault longer than the window sits inside its own reference and is partly
 *  absorbed by it, so the station looks healthier than it is. The API computes
 *  this per item rather than asserting a fixed sentence. */
export interface ReferenceNote {
  kind: string
  window_hours: number
  fault_hours: number
  compromised: boolean
  warning: string
}

/** GET /api/queue */
export interface QueueResponse {
  generated_from: string
  stations_scanned: number
  windows_scanned: number
  items: QueueItem[]
  actions: Record<string, number>
  /** Non-null only when every item carries the same action, explaining why the
   *  corpus cannot show the other branch. */
  action_note: string | null
  scorecard: Scorecard
}

export interface Scorecard {
  analyst_named: number
  we_raised_of_those: number
  we_missed: string[]
  items_raised: number
  raised_and_confirmed: number
  recall: number | null
  /** A LOWER BOUND, not a true precision -- ARM reports what someone noticed,
   *  not everything that was wrong. Always render the caveat with it. */
  precision_vs_analyst: number | null
  caveat: string
}

/** One checker's opinion at one instant. Six run as a panel. */
export interface Verdict {
  checker: 'physics' | 'neighbour' | 'history' | 'instrument' | 'clock' | 'hardware' | string
  fired: boolean
  score: number | null
  reason: string
}

/** GET /api/queue/{id} -- the queue item plus the evidence behind it. */
export interface QueueItemDetail extends QueueItem {
  /** The hour the panel was evaluated at: the moment the evidence was
   *  strongest, not the most recent hour. */
  at: string
  panel_note: string
  verdicts: Verdict[]
  decision: string
  note: string | null
  explain: string
  series: Series
  analyst_note: string
}

/** Parallel arrays, not an array of objects: these run to thousands of hourly
 *  points and the columnar form is what uPlot consumes without a reshape. */
export interface Series {
  t: string[]
  v: (number | null)[]
  /** RAW bias, in the sensor's own units. Almost never what you want to plot:
   *  tolerance is |bias| <= 2 * noise, not |bias| <= 2. Divide by `noise` and
   *  the result is directly comparable to `severity` on the item. */
  bias: (number | null)[]
  /** The noise the estimator held at each step. Present so a client can put
   *  bias in units of it rather than assuming a constant band. */
  noise: (number | null)[]
  trust: (number | null)[]
  faulty: boolean[]
}

/** GET /api/ai/catalog */
export interface CatalogResponse {
  stations: CatalogStation[]
  source: string
}

export interface CatalogStation {
  station: string
  windows: CatalogWindow[]
  best_days: number
}

export interface CatalogWindow {
  dqr: string
  subject: string
  start: string
  end: string
  hours: number
  variables: string
  days_held: number
  housekeeping_named: boolean
}

/** One simulated Indian station. GET /api/stations
 *
 * These are the DEPLOYMENT network: the stations SkyGuard is built to watch.
 * They are simulated from ERA5 reanalysis, because IMD does not publish a
 * per-instrument fault archive. The instruments the detector is VALIDATED on
 * are the real ARM sites in api/sites.ts, and the two are never mixed. */
export interface Station {
  name: string
  state: string
  cluster: string
  elevation: number
  longitude: number
  latitude: number
  neighbours: string[]
  sigma: Record<string, number>
  health: {
    station: string
    by_variable: Record<string, string>
    health_version: string
  }
  alert_count?: number
}

/** GET /api/tiles/status -- the map's own account of whether it can draw.
 *
 * The templates carry a version hash, so they are read from here rather than
 * hardcoded: a cache rebuild changes the hash and hardcoded URLs would quietly
 * start serving stale tiles. */
export interface TileStatus {
  available: boolean
  upstream_reachable: { basemap: boolean; boundary: boolean }
  cached_tiles: number
  attribution: string
  version: string
  tile_template: string
  boundary_template: string
  official_indian_boundary_source: boolean
  max_zoom: number
}
