"""Drive the Wokwi node's sensors from the simulated weather field.

WHAT PROBLEM THIS SOLVES

Until now the ESP32 in Wokwi read whatever the knobs happened to be set to: a
DHT22 sitting at its default 24 C and 40 %, and a potentiometer standing in for
the barometer. The firmware was real, the plumbing was real, and the data was
furniture. Nothing in the recording looked like weather, so nothing downstream
could be judged -- a residual against neighbours is meaningless when the
"sensor" is a slider somebody left alone.

This writes a Wokwi automation scenario that steps the sensors through the SAME
field the 344 simulated stations are drawn from, sampled at the node's own
location. The node then measures a real diurnal cycle, its readings differ from
its neighbours only by sensor noise, and the server's neighbour differencing has
something to difference.

WHERE THE NUMBERS COME FROM

`api.live._expected` -- the inverse-distance estimate from the six nearest
simulated stations at that frame -- plus the same per-channel sensor noise the
Python feeder uses. Deliberately the same functions rather than a second copy of
the weather model: two generators that drift apart would show a node failing for
reasons that live in this script.

The injected fault uses the same vocabulary as `simulate/faults_and_export.py`,
for the same reason.

USAGE

    python -m scripts.make_wokwi_scenario                    # clean run
    python -m scripts.make_wokwi_scenario --fault drift      # drift from halfway
    python -m scripts.make_wokwi_scenario --samples 300 --start-frame 96

Then, from firmware/skyguard_node:

    wokwi-cli --scenario weather-scenario.yaml --timeout 900000 .
"""
from __future__ import annotations

import argparse
import random
from pathlib import Path

# The knob's travel in the firmware: p = PRES_LO + (PRES_HI - PRES_LO) * pos.
# Kept in step with skyguard_node.ino by hand, and asserted below, because a
# silent mismatch would show up as a pressure offset nobody could explain.
PRES_LO, PRES_HI = 950.0, 1050.0

# The DHT22's own limits. Values outside these are what the part will refuse to
# represent, not what the weather does -- clamping here keeps the scenario a
# statement about weather rather than about the model of the sensor.
DHT_T = (-40.0, 80.0)
DHT_H = (0.0, 100.0)

OUT = Path(__file__).resolve().parent.parent / "firmware" / "skyguard_node" / "weather-scenario.yaml"


def _clamp(v, lo, hi):
    return max(lo, min(hi, v))


def build(samples: int, start_frame: int, sample_ms: int, station: str,
          fault: str, fault_at: float, seed: int,
          drift_per_day: float) -> str:
    from api.edge_grade import EDGE_STATIONS
    from api.live import SENSOR_NOISE, _expected, _neighbours, _sim

    if station not in EDGE_STATIONS:
        raise SystemExit("%s is not a registered edge station" % station)
    st = EDGE_STATIONS[station]

    sim = _sim()
    import base64
    n_frames = len(base64.b64decode(sim["stations"][0]["vt"]))
    nbrs = _neighbours(sim, st["lat"], st["lon"], k=6)

    rng = random.Random(seed)
    onset = int(samples * fault_at)

    lines = [
        "# Weather for the SkyGuard node, taken from the simulated field.",
        "#",
        "# GENERATED by scripts/make_wokwi_scenario.py -- do not hand-edit;",
        "# regenerate instead, or the readings stop matching the network the",
        "# server compares them against.",
        "#",
        "# Station : %s at %.4f, %.4f (%s)" % (station, st["lat"], st["lon"],
                                               st["state"]),
        "# Field   : %d frames of 30 simulated minutes, starting at frame %d"
        % (n_frames, start_frame),
        "# Samples : %d, one every %d ms of wall clock" % (samples, sample_ms),
        "# Fault   : %s%s" % (fault,
                              "" if fault == "none"
                              else " from sample %d%s"
                              % (onset,
                                 ", %.2f K per simulated day" % drift_per_day
                                 if fault == "drift" else "")),
        "#",
        "# Each step sets the DHT22 to the temperature and humidity the node's",
        "# neighbours say this place should be reading, plus this sensor's own",
        "# noise, and turns the pressure knob to the matching position.",
        "",
        "name: skyguard-node-weather",
        "version: 1",
        "author: SkyGuard / SIH 2026 PS26073",
        "",
        "steps:",
        "  - wait-serial: \"SkyGuard node\"",
        "",
    ]

    for i in range(samples):
        frame = (start_frame + i) % n_frames
        t, h, p = _expected(sim, frame, nbrs)
        t += rng.gauss(0, SENSOR_NOISE["temp"])
        h += rng.gauss(0, SENSOR_NOISE["rh"])
        p += rng.gauss(0, SENSOR_NOISE["pres"])

        # THE FAULT IS APPLIED TO THE SENSOR, NOT TO THE MESSAGE.
        #
        # This is the whole reason the scenario is worth generating: the node's
        # firmware is not told anything. It reads a probe that has started
        # lying, screens it, and decides on its own whether to transmit -- which
        # is what a failing instrument actually looks like from the board's
        # point of view.
        if fault != "none" and i >= onset:
            k = i - onset
            if fault == "drift":
                # WHY THE DEMO RATE IS NOT THE STUDY RATE.
                #
                # evaluation/run_edge_approx.py is built around 0.02 K/day,
                # and at that rate this detector needs about 131 days to reach
                # the 6-sigma band. A 2.5-day scenario at 0.02 K/day would
                # accumulate 0.05 K -- a fifth of the sensor noise -- and show
                # a detector detecting nothing, which is not a kinder demo, it
                # is a misleading one.
                #
                # So the rate is a parameter, printed by the generator with the
                # sample at which it crosses. Half an hour per sample means 48
                # samples to the simulated day.
                t += drift_per_day * (k / 48.0)
            elif fault == "offset":
                t += 2.0
            elif fault == "stuck":
                t, h, p = _stuck_values(sim, nbrs, start_frame + onset,
                                        n_frames)
            elif fault == "spike":
                if k % 20 == 0:
                    t += 12.0

        t = _clamp(t, *DHT_T)
        h = _clamp(h, *DHT_H)
        pos = _clamp((p - PRES_LO) / (PRES_HI - PRES_LO), 0.0, 1.0)

        lines += [
            "  # sample %-4d frame %-5d  %5.1f C  %4.1f %%  %7.2f hPa%s"
            % (i, frame, t, h, p,
               "  <- %s" % fault if fault != "none" and i >= onset else ""),
            "  - set-control:",
            "      part-id: dht",
            "      control: temperature",
            "      value: %.2f" % t,
            "  - set-control:",
            "      part-id: dht",
            "      control: humidity",
            "      value: %.1f" % h,
            "  - set-control:",
            "      part-id: pres",
            "      control: position",
            "      value: %.4f" % pos,
            "  - delay: %dms" % sample_ms,
            "",
        ]

    return "\n".join(lines)


def _stuck_values(sim, nbrs, frame, n_frames):
    """A frozen probe repeats the reading it had when it failed."""
    from api.live import _expected
    return _expected(sim, frame % n_frames, nbrs)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--samples", type=int, default=240,
                    help="how many readings to script (default 240 = 5 "
                         "simulated days)")
    ap.add_argument("--start-frame", type=int, default=0,
                    help="frame of the record to start at (30 min each)")
    ap.add_argument("--sample-ms", type=int, default=2000,
                    help="wall-clock gap between samples; must match "
                         "SAMPLE_MS in skyguard_node.ino")
    ap.add_argument("--station", default="WOKWI-ESP32")
    ap.add_argument("--fault", default="none",
                    choices=("none", "drift", "offset", "stuck", "spike"))
    ap.add_argument("--fault-at", type=float, default=0.5,
                    help="fraction of the run at which the fault starts")
    ap.add_argument("--drift-per-day", type=float, default=1.0,
                    help="drift rate in K per simulated day. The measured "
                         "study rate is 0.02, which needs ~131 days to reach "
                         "6 sigma; the default here is a rate that crosses "
                         "inside the run so the demo shows a detection")
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    text = build(args.samples, args.start_frame, args.sample_ms,
                 args.station, args.fault, args.fault_at, args.seed,
                 args.drift_per_day)
    Path(args.out).write_text(text, encoding="utf-8")

    sim_hours = args.samples * 0.5
    print("wrote %s" % args.out)
    print("  %d samples, %.1f simulated hours, %.1f minutes of wall clock"
          % (args.samples, sim_hours, args.samples * args.sample_ms / 60000.0))
    if args.fault == "drift":
        # Roughly where it becomes visible: the residual scale is the sensor
        # noise, and WATCH is six of them.
        from api.live import SENSOR_NOISE
        need = 6.0 * SENSOR_NOISE["temp"]
        days = need / max(args.drift_per_day, 1e-9)
        onset = int(args.samples * args.fault_at)
        print("  fault: drift, %.2f K/simulated day from sample %d"
              % (args.drift_per_day, onset))
        print("  crosses ~6 sigma (%.2f K) after %.1f simulated days "
              "= sample %d" % (need, days, onset + int(days * 48)))
    else:
        print("  fault: %s" % args.fault)


if __name__ == "__main__":
    main()
