"""The map's data, served over HTTP instead of inlined into a page.

WHY THIS EXISTS

The static console carries every one of these files inside itself -- the build
substitutes them into console.html, which is why that page is 2.6 MB. That was
the right trade for a page that had to work with no server at all.

The React app is served by this API, so it has a server by definition, and
inlining 2.6 MB into a JavaScript bundle would be strictly worse: the bundle is
parsed on every load, the browser cannot cache the data separately from the
code, and changing one station's grade would invalidate the whole bundle.

So the same files are served as JSON, with long cache lifetimes because they are
regenerated by an explicit build step rather than continuously.

WHAT IS HERE, AND WHERE EACH COMES FROM

    /api/map/sim        dashboard/sim_map.json      simulate.faults_and_export
    /api/map/wdqms      dashboard/wdqms.json        dashboard.export_wdqms
    /api/map/arm        dashboard/arm_sites.json    dashboard.export_arm_sites
    /api/map/states     vendor/india_states.min.json  dashboard.simplify_states
    /api/map/boundary   vendor/india_boundary.min.json  vendored from NCMRWF

None of them is generated here. If a file is missing the endpoint says which
command produces it, because "404" on a data file is a build step someone has
not run, not a bug to be debugged.
"""
from __future__ import annotations

import os
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter()

_DASH = Path(os.path.dirname(os.path.dirname(__file__))) / "dashboard"

# name -> (path, the command that regenerates it)
FILES: dict[str, tuple[Path, str]] = {
    "sim": (_DASH / "sim_map.json", "python -m simulate.faults_and_export"),
    "wdqms": (_DASH / "wdqms.json", "python -m dashboard.export_wdqms"),
    "arm": (_DASH / "arm_sites.json", "python -m dashboard.export_arm_sites"),
    "states": (_DASH / "vendor" / "india_states.min.json",
               "python -m dashboard.simplify_states"),
    "boundary": (_DASH / "vendor" / "india_boundary.min.json",
                 "vendored; see dashboard/vendor/"),
}


@router.get("/api/map/{name}")
def map_data(name: str):
    if name not in FILES:
        raise HTTPException(404, f"unknown map dataset {name!r}; "
                                 f"have {', '.join(sorted(FILES))}")
    path, how = FILES[name]
    if not path.exists():
        # Say what to run. A missing export is a step someone skipped, and a
        # bare 404 sends them into the network tab looking for a routing fault.
        raise HTTPException(404, f"{path.name} has not been generated. Run: {how}")
    return FileResponse(
        path, media_type="application/json",
        # These change only when a build is run, so a long cache is honest. The
        # browser still revalidates on reload, and the console's own copy is
        # unaffected either way.
        # Revalidate every time. These files are regenerated by a build step,
        # and an hour of blind caching meant a re-graded export sat behind the
        # old one -- the board went on reporting numbers from a detector that
        # had already been replaced, which is the worst kind of stale: it looks
        # like a result. ETag/Last-Modified still make the revalidation cheap.
        headers={"Cache-Control": "no-cache"},
    )


@router.get("/api/map")
def map_index() -> dict:
    """What is available and what is missing, with the command for each."""
    return {
        "datasets": [
            {"name": n, "url": f"/api/map/{n}", "available": p.exists(),
             "bytes": (p.stat().st_size if p.exists() else 0), "generated_by": how}
            for n, (p, how) in sorted(FILES.items())
        ]
    }


@router.get("/api/summary")
def summary() -> dict:
    """What the front page needs, and nothing it does not.

    The landing page wants five numbers. Reading them out of /api/map/sim would
    make a visitor download 5.7 MB of station-by-station grades to be told there
    are 344 stations -- so the counts are computed here, once, and cached.

    The measured figures are quoted from the runs recorded in the repository
    rather than recomputed on request: they come from a sweep against known
    injected faults, and a number that changes between page loads is not the
    number that was measured.
    """
    import json
    from functools import lru_cache

    @lru_cache(maxsize=1)
    def _counts() -> tuple[int, int, int, str]:
        p = _DASH / "sim_map.json"
        if not p.exists():
            return 0, 0, 0, ""
        d = json.loads(p.read_text(encoding="utf-8"))
        st = d["stations"]
        states = {s.get("state") for s in st if s.get("state")}
        faulty = sum(1 for s in st if s.get("fault"))
        return len(st), len(states), faulty, d.get("t0", "")

    n, n_states, faulty, t0 = _counts()
    return {
        "network": {
            "simulated_stations": n,
            "states": n_states,
            "injected_faults": faulty,
            "days": 30,
            "step_minutes": 15,
            "t0": t0,
        },
        "parameters": ["temperature", "pressure", "relative humidity"],
        "measured": {
            # From the calibration sweep in simulate/faults_and_export.py.
            "recall": 0.57,
            "precision": 0.38,
            "recall_excluding_dropouts": 0.72,
            "alert_episodes": 73,
            "stations_alerting": 42,
            "note": "Bands calibrated at 6 and 8 sigma against a fault-free "
                    "control run. Dropouts are excluded from the second recall "
                    "figure because a station that stops reporting has no "
                    "residual to difference -- it is NO DATA, not a fault.",
        },
        "validation": {
            "corpus": "the injected faults in this network",
            "why": "Truth is known by construction: the generator records what "
                   "it injected and where, and the grader is never shown it. "
                   "That is what makes recall and precision exact figures here "
                   "rather than estimates.",
        },
    }
