"""The map's data, served over HTTP instead of inlined into a page.

WHY THIS EXISTS

The static console carries every one of these files inside itself -- the build
substitutes them into console.html, which is why that page is 2.6 MB. That was
the right trade for a page that had to work with no server at all.

The React app is served by this API, so it has a server by definition, and
inlining 2.6 MB into a JavaScript bundle would be strictly worse: the bundle is
parsed on every load, the browser cannot cache the data separately from the
code, and changing one station's grade would invalidate the whole bundle.

So the same files are served as JSON, with long cache lifetimes because they are
regenerated by an explicit build step rather than continuously.

WHAT IS HERE, AND WHERE EACH COMES FROM

    /api/map/sim        dashboard/sim_map.json      simulate.faults_and_export
    /api/map/wdqms      dashboard/wdqms.json        dashboard.export_wdqms
    /api/map/arm        dashboard/arm_sites.json    dashboard.export_arm_sites
    /api/map/states     vendor/india_states.min.json  dashboard.simplify_states
    /api/map/boundary   vendor/india_boundary.min.json  vendored from NCMRWF

None of them is generated here. If a file is missing the endpoint says which
command produces it, because "404" on a data file is a build step someone has
not run, not a bug to be debugged.
"""
from __future__ import annotations

import os
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter()

_DASH = Path(os.path.dirname(os.path.dirname(__file__))) / "dashboard"

# name -> (path, the command that regenerates it)
FILES: dict[str, tuple[Path, str]] = {
    "sim": (_DASH / "sim_map.json", "python -m simulate.faults_and_export"),
    "wdqms": (_DASH / "wdqms.json", "python -m dashboard.export_wdqms"),
    "arm": (_DASH / "arm_sites.json", "python -m dashboard.export_arm_sites"),
    "states": (_DASH / "vendor" / "india_states.min.json",
               "python -m dashboard.simplify_states"),
    "boundary": (_DASH / "vendor" / "india_boundary.min.json",
                 "vendored; see dashboard/vendor/"),
}


@router.get("/api/map/{name}")
def map_data(name: str):
    if name not in FILES:
        raise HTTPException(404, f"unknown map dataset {name!r}; "
                                 f"have {', '.join(sorted(FILES))}")
    path, how = FILES[name]
    if not path.exists():
        # Say what to run. A missing export is a step someone skipped, and a
        # bare 404 sends them into the network tab looking for a routing fault.
        raise HTTPException(404, f"{path.name} has not been generated. Run: {how}")
    return FileResponse(
        path, media_type="application/json",
        # These change only when a build is run, so a long cache is honest. The
        # browser still revalidates on reload, and the console's own copy is
        # unaffected either way.
        # Revalidate every time. These files are regenerated by a build step,
        # and an hour of blind caching meant a re-graded export sat behind the
        # old one -- the board went on reporting numbers from a detector that
        # had already been replaced, which is the worst kind of stale: it looks
        # like a result. ETag/Last-Modified still make the revalidation cheap.
        headers={"Cache-Control": "no-cache"},
    )


@router.get("/api/map")
def map_index() -> dict:
    """What is available and what is missing, with the command for each."""
    return {
        "datasets": [
            {"name": n, "url": f"/api/map/{n}", "available": p.exists(),
             "bytes": (p.stat().st_size if p.exists() else 0), "generated_by": how}
            for n, (p, how) in sorted(FILES.items())
        ]
    }
